-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 23:36:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserEmail` VARCHAR(45) NULL,
  `UserLogin` VARCHAR(45) NULL,
  `UserPass` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NULL,
  `ItemsSelling` VARCHAR(45) NULL,
  `Admin` VARCHAR(45) NULL,
  `Recomendations` VARCHAR(45) NULL,
  `Reports` VARCHAR(45) NULL,
  `Verification` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Offers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `category` VARCHAR(45) NULL,
  `price` VARCHAR(45) NULL,
  `condition` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `shipment` VARCHAR(45) NULL,
  `payment` VARCHAR(45) NULL,
  `User_ID` INT NOT NULL,
  PRIMARY KEY (`id`, `User_ID`),
  INDEX `fk_Offers_User1_idx` (`User_ID` ASC),
  CONSTRAINT `fk_Offers_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserHistory` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserPurchases` VARCHAR(45) NULL,
  `UserSells` VARCHAR(45) NULL,
  `Offers_id` INT NOT NULL,
  `User_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Offers_id`, `User_ID`),
  INDEX `fk_UserHistory_Offers_idx` (`Offers_id` ASC),
  INDEX `fk_UserHistory_User1_idx` (`User_ID` ASC) ,
  CONSTRAINT `fk_UserHistory_Offers`
    FOREIGN KEY (`Offers_id`)
    REFERENCES `mydb`.`Offers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UserHistory_User1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `mydb`.`User` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
